openapi: 3.2.0
info:
  version: 1.0.0
  title: Angle Tvl API
  description: API to track the Angle Protocol state
servers:
- url: https://api.angle.money
tags:
- name: TVL
paths:
  /v1/tvl:
    get:
      description: Return the TVL of the Angle Protocol on the requested chain
      parameters:
      - name: chainId
        in: query
        description: Chain requested - Default is 1 (Ethereum mainnet)
        schema:
          type: integer
      responses:
        '200':
          description: Angle TVL on the requested chain
      tags:
      - TVL
      summary: Get tvl
      x-summary-source: derived
      operationId: getV1Tvl
      x-operation-id-source: derived
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
