openapi: 3.0.0
info:
  version: 1.0.0
  title: Angle Allowances Volume API
  description: API to track the Angle Protocol state
servers:
- url: https://api.angle.money
tags:
- name: Volume
paths:
  /v1/volume:
    get:
      description: Return data related to the agEUR volume on a given chain
      parameters:
      - name: chainId
        in: query
        description: Chain requested
        schema:
          type: integer
      responses:
        '200':
          description: agEUR volume and circulating supply data on the requested chain
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/volume'
      tags:
      - Volume
components:
  schemas:
    volume:
      type: object
      properties:
        circulatingSupply:
          type: number
          description: Total circulating supply of the token
        holder:
          type: number
          description: Number of addresses holding the token
        rate:
          type: number
          description: Per second increase rate of the agEUR volume over the last 30 minutes based on `Transfer` event
        volume:
          type: number
          description: Per second agEUR volume based on `Transfer` event
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
